In [1]:
import pandas as pd
import os
import kagglehub
import shutil

c:\Users\felip\OneDrive\git_work\Flavors-of-Cacao-2006-2024\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
os.makedirs('../data/processed', exist_ok=True)
os.makedirs('../data/datasets', exist_ok=True)
os.makedirs('../data/datasets/flavors_of_cacao', exist_ok=True)

In [9]:
# Download da versão mais recente do dataset
path = kagglehub.dataset_download("christopherzaman/flavors-of-cacao-2025")
print("Path temporário do dataset:", path)

# Define o destino relativo ao notebook
dest_dir = os.path.join(os.path.dirname(os.getcwd()), "data", "datasets",'flavors_of_cacao')

# Copia os arquivos do cache do kagglehub para o destino
for arquivo in os.listdir(path):
    src = os.path.join(path, arquivo)
    dst = os.path.join(dest_dir, arquivo)
    shutil.copy2(src, dst)
    print(f"Copiado: {arquivo}")

print(f"\nDataset salvo em: {dest_dir}")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.10), please consider upgrading to the latest version (1.0.0).
Path temporário do dataset: C:\Users\felip\.cache\kagglehub\datasets\christopherzaman\flavors-of-cacao-2025\versions\1
Copiado: flavors-of-cacao-2025.csv

Dataset salvo em: c:\Users\felip\OneDrive\git_work\Flavors-of-Cacao-2006-2024\data\datasets\flavors_of_cacao

In [2]:
df = pd.read_csv('../data/datasets/flavors_of_cacao/flavors-of-cacao-2025.csv')

In [3]:
df.head()

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,2454,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76%,"3- B,S,C","cocoa, blackberry, full body",3.75
1,2458,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76%,"3- B,S,C","cocoa, vegetal, savory",3.50
2,2454,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76%,"3- B,S,C","rich cocoa, fatty, bready",3.25
3,2542,5150,U.S.A.,2021,India,"Anamalai, batch 1",68%,"3- B,S,C","milk brownie, macadamia,chewy",3.50
4,2546,5150,U.S.A.,2021,Uganda,"Semuliki Forest, batch 1",80%,"3- B,S,C","mildly bitter, basic cocoa, fatty",3.25

In [35]:
lista = df['Company Location'].unique()
lista

<StringArray>
[               'U.S.A.',             'Venezuela',                'France',
                 'Japan',                  'Fiji',               'Vanuatu',
               'Ecuador',                'Mexico',                  'U.K.',
           'Netherlands',                'Canada',                 'Spain',
                'Russia',                  'Peru',                 'Italy',
                'Brazil',             'Nicaragua',             'Nicaraqua',
             'Australia',           'Philippines',                 'Wales',
              'Scotland',             'Lithuania',               'Belgium',
           'El Salvador',               'Vietnam',               'Germany',
             'Singapore',           'Switzerland',              'Malaysia',
           'South Korea',                'Taiwan',           'Puerto Rico',
              'Colombia',           'New Zealand',            'Costa Rica',
               'Hungary',               'Estonia',            'Martinique',
   'Sao Tome & Principe',             'St. Lucia',             'Argentina',
             'Guatemala',          'South Africa',                 'China',
    'Dominican Republic',               'Bolivia',              'Portugal',
                'Norway',               'Denmark',               'Grenada',
                'Israel',                 'India', 'St.Vincent-Grenadines',
        'Czech Republic',              'Thailand',               'Finland',
               'Romania',            'Madagascar',                'Sweden',
                'Poland',               'Austria',              'Honduras',
                'U.A.E.',               'Ireland',                 'Chile',
                 'Benin',                 'Ghana',               'Iceland',
               'Jamaica',              'Suriname']
Length: 71, dtype: str

In [28]:
df_2 = df.copy()

In [29]:
df_2['Rating'] = df_2['Rating'].astype(str)

In [30]:
df_2['Rating']

0       3.75
1        3.5
2       3.25
3        3.5
4       3.25
        ...
2784    2.75
2785    3.75
2786     3.5
2787    3.25
2788     3.0
Name: Rating, Length: 2789, dtype: str

In [31]:
df_2['Rating'] = df_2['Rating'].str.replace('.',',')

In [33]:
df_2['Cocoa Percent'] = df_2['Cocoa Percent'].str.replace('%','')

In [36]:
df_2['Company Location'] = df_2['Company Location'].str.replace('.','')

In [37]:
df_2.head()

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,2454,5150,USA,2019,Madagascar,"Bejofo Estate, batch 1",76,"3- B,S,C","cocoa, blackberry, full body","3,75"
1,2458,5150,USA,2019,Dominican Republic,"Zorzal, batch 1",76,"3- B,S,C","cocoa, vegetal, savory","3,5"
2,2454,5150,USA,2019,Tanzania,"Kokoa Kamili, batch 1",76,"3- B,S,C","rich cocoa, fatty, bready","3,25"
3,2542,5150,USA,2021,India,"Anamalai, batch 1",68,"3- B,S,C","milk brownie, macadamia,chewy","3,5"
4,2546,5150,USA,2021,Uganda,"Semuliki Forest, batch 1",80,"3- B,S,C","mildly bitter, basic cocoa, fatty","3,25"

In [38]:
lista = df_2['Company Location'].unique()
lista

<StringArray>
[                 'USA',            'Venezuela',               'France',
                'Japan',                 'Fiji',              'Vanuatu',
              'Ecuador',               'Mexico',                   'UK',
          'Netherlands',               'Canada',                'Spain',
               'Russia',                 'Peru',                'Italy',
               'Brazil',            'Nicaragua',            'Nicaraqua',
            'Australia',          'Philippines',                'Wales',
             'Scotland',            'Lithuania',              'Belgium',
          'El Salvador',              'Vietnam',              'Germany',
            'Singapore',          'Switzerland',             'Malaysia',
          'South Korea',               'Taiwan',          'Puerto Rico',
             'Colombia',          'New Zealand',           'Costa Rica',
              'Hungary',              'Estonia',           'Martinique',
  'Sao Tome & Principe',             'St Lucia',            'Argentina',
            'Guatemala',         'South Africa',                'China',
   'Dominican Republic',              'Bolivia',             'Portugal',
               'Norway',              'Denmark',              'Grenada',
               'Israel',                'India', 'StVincent-Grenadines',
       'Czech Republic',             'Thailand',              'Finland',
              'Romania',           'Madagascar',               'Sweden',
               'Poland',              'Austria',             'Honduras',
                  'UAE',              'Ireland',                'Chile',
                'Benin',                'Ghana',              'Iceland',
              'Jamaica',             'Suriname']
Length: 71, dtype: str

In [41]:
import pandas as pd
from deep_translator import GoogleTranslator

# 1. Inicializar o tradutor (mais robusto que o googletrans)
translator = GoogleTranslator(source='en', target='pt')

# 2. Pegar os valores únicos para economizar tempo/API
valores_unicos = df_2['Company Location'].unique()

# 3. Criar o dicionário de tradução
mapa_traducao = {}
print("Iniciando tradução...")

for texto in valores_unicos:
    try:
        # A deep-translator não costuma dar o erro de 'NoneType'
        traducao = translator.translate(texto)
        mapa_traducao[texto] = traducao
    except Exception as e:
        print(f"Erro ao traduzir '{texto}': {e}")
        mapa_traducao[texto] = texto

# 4. Aplicar na coluna
df_2['Company Location PT'] = df_2['Company Location'].map(mapa_traducao)

print("Tradução concluída!")
df_2[['Company Location', 'Company Location PT']].head()

Iniciando tradução...
Tradução concluída!

  Company Location Company Location PT
0              USA                 EUA
1              USA                 EUA
2              USA                 EUA
3              USA                 EUA
4              USA                 EUA

In [42]:
df_2

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating,Company Location PT
0,2454,5150,USA,2019,Madagascar,"Bejofo Estate, batch 1",76,"3- B,S,C","cocoa, blackberry, full body","3,75",EUA
1,2458,5150,USA,2019,Dominican Republic,"Zorzal, batch 1",76,"3- B,S,C","cocoa, vegetal, savory","3,5",EUA
2,2454,5150,USA,2019,Tanzania,"Kokoa Kamili, batch 1",76,"3- B,S,C","rich cocoa, fatty, bready","3,25",EUA
3,2542,5150,USA,2021,India,"Anamalai, batch 1",68,"3- B,S,C","milk brownie, macadamia,chewy","3,5",EUA
4,2546,5150,USA,2021,Uganda,"Semuliki Forest, batch 1",80,"3- B,S,C","mildly bitter, basic cocoa, fatty","3,25",EUA
...,...,...,...,...,...,...,...,...,...,...,...
2784,1205,Zotter,Austria,2014,Blend,Raw,80,"4- B,S*,C,Sa","waxy, cloying, vegetal","2,75",Áustria
2785,1996,Zotter,Austria,2017,Colombia,"APROCAFA, Acandi",75,"3- B,S,C","strong nutty, marshmallow","3,75",Áustria
2786,2170,Zotter,Austria,2018,Belize,Maya Mtn,72,"3- B,S,C","muted, roasty, accessible","3,5",Áustria
2787,2170,Zotter,Austria,2018,Congo,Mountains of the Moon,70,"3- B,S,C","fatty, mild nuts, mild fruit","3,25",Áustria
2788,2036,Zotter,Austria,2018,Blend,"Dry Aged, 30 yr Anniversary bar",75,"3- B,S,C","fatty, earthy, cocoa","3,0",Áustria

In [1]:
df_2.to_csv('../data/processed/flavors_of_cacao_2006_2024_processed.csv')

NameError: name 'df_2' is not defined